name: Update Test Durations

# This workflow updates test durations based on the latest nightly, weekly, weekly training and push workflow runs.
# It processes the JUnit XML reports from the last successful nightly, weekly, weekly training and push workflows,
# calculates the test durations, and creates a pull request to update the `.test_durations` file.

on:
  workflow_dispatch:

permissions:
  packages: write
  checks: write

jobs:
  update_test_durations:
    runs-on: multihost_experimental
    container:
      image: ghcr.io/tenstorrent/tt-xla-ci:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run hello script
        run: |
          echo "hello"
          hostname
          touch hello
          sleep 6000
